version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=10000'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=mediumclone
      - POSTGRES_PASSWORD=mediumclone
      - POSTGRES_DB=mediumclone
    ports:
      - '5433:5432'
